/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class Japi */

#ifndef _Included_Japi
#define _Included_Japi
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     Japi
 * Method:    InitSocket
 * Signature: (Ljava/lang/String;II)J
 */
JNIEXPORT jlong JNICALL Java_Japi_InitSocket
  (JNIEnv *, jobject, jstring, jint, jint);

/*
 * Class:     Japi
 * Method:    Connect
 * Signature: (JLjava/lang/String;Ljava/lang/String;IIII)Z
 */
JNIEXPORT jboolean JNICALL Java_Japi_Connect
  (JNIEnv *, jobject, jlong, jstring, jstring, jint, jint, jint, jint);

/*
 * Class:     Japi
 * Method:    Disconnect
 * Signature: (JLjava/lang/String;Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_Japi_Disconnect
  (JNIEnv *, jobject, jlong, jstring, jstring);

/*
 * Class:     Japi
 * Method:    Send
 * Signature: (JLjava/lang/String;Ljava/lang/String;[BI)Z
 */
JNIEXPORT jboolean JNICALL Java_Japi_Send
  (JNIEnv *, jobject, jlong, jstring, jstring, jbyteArray, jint);

/*
 * Class:     Japi
 * Method:    Flush
 * Signature: (JLjava/lang/String;Ljava/lang/String;)Z
 */
JNIEXPORT jboolean JNICALL Java_Japi_Flush
  (JNIEnv *, jobject, jlong, jstring, jstring);

/*
 * Class:     Japi
 * Method:    WaitUntilTxIsCompleted
 * Signature: (JLjava/lang/String;Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_Japi_WaitUntilTxIsCompleted
  (JNIEnv *, jobject, jlong, jstring, jstring);

/*
 * Class:     Japi
 * Method:    Receive
 * Signature: (J[BLjava/lang/String;Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_Japi_Receive
  (JNIEnv *, jobject, jlong, jbyteArray, jstring, jstring);

/*
 * Class:     Japi
 * Method:    FreeSocket
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_Japi_FreeSocket
  (JNIEnv *, jobject, jlong);

#ifdef __cplusplus
}
#endif
#endif
